name: flutter_architecture
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

isar_version: &isar_version ^3.1.0 # define the version to be used


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.3
  get_it: ^7.6.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  uuid: ^4.0.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.1
flutter:
  uses-material-design: true
